[package]
name = "metaheuristics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
plotters-backend = "0.3"
plotters = "0.3"
eframe = "0.22.0"
egui-plotter = "0.3.0"
